### ISSUE TITLE
Bibtex Citation

### ISSUE THREAD

**Issue by Zasder3** [FreddeFrallan/Multilingual-CLIP#11]
Amazing repo! I'd love to cite it. Do you have a desired `bibtex` by chance?

Perhaps:

@misc{multilingual-clip,
  author          = {Carlsson, Fredrik},
  title           = {Multilingual CLIP},
  year            = 2021,
  publisher       = {GitHub},
  journal         = {GitHub repository},
  howpublished    = {\url{https://github.com/SajjjadAyobi/CLIPfa}},
}

**Comment by FreddeFrallan** [comment]
Heeey, thanks for wanting to put your citation here.
There is an accepted short paper for this work at LREC 2022
https://lrec2022.lrec-conf.org/en/conference-programme/accepted-papers/

For whatever reason, I can't seem to find any released Bibtex yet. But they should release that any day now I guess.
Considering that the conference is in June.
