### ISSUE TITLE
Support ViT-B/32 of Vision Model

### ISSUE THREAD

**Issue by tommy19970714** [FreddeFrallan/Multilingual-CLIP#2]
Incredible work done here - congratulations on the fantastic results.
Do you have plan to support ViT-B/32 of Vision Model?

**Comment by FreddeFrallan** [comment]
Thank you, it's funny how many people seem to find this weekend hack useful!
I could re-run an experiment for the ViT-B/32, is there any specific language you had in mind?

**Comment by tommy19970714** [comment]
I want to combine Multilingual-CLIP with [StyleCLIP](https://github.com/orpatashnik/StyleCLIP).
It only supports English now.
If we use Multilingual-CLIP, we think we can transform faces in several languages.
However, StyleCLIP only supports ViT-B/32.

**Comment by FreddeFrallan** [comment]
Got it!
I'll start a training for the ViT-B/32 this weekend.

**Comment by FreddeFrallan** [comment]
I have now uploaded the multilingual text encoder for ViT-B/32.
As for all the other models, I have not tested the quality! 

Hope you find it useful :)

**Comment by tommy19970714** [comment]
Awesome! Thank you very much!
I will try text encoder of ViT-B/32.
