### ISSUE TITLE
1024 dim embedding model needed 

### ISSUE THREAD

**Issue by ithanwu** [FreddeFrallan/Multilingual-CLIP#23]
Dear authors ,
Thx 4 your Great work ! 
But I'm  working with AudioClip of which the embeddings are 1024 dims, But the models U've released have most 768 dims,
Could U pls kindly release a model that can produce 1024 dims embedding ?
Here is AudioClip : https://github.com/AndreyGuzhov/AudioCLIP
With my best wish !
Looking forward to hearing from U !

**Comment by ithanwu** [comment]
@FreddeFrallan @Zasder3 @rom1504

**Comment by rom1504** [comment]
Can you try to follow the instructions in the repo, train one ?
Please say if anything is unclear

**Comment by ithanwu** [comment]
ok ,thx 4 your reply ,I'll try ,if some problem occur it would depend on your help , when it's finished I can share this model

**Comment by FreddeFrallan** [comment]
Sounds good, let us know if we can help :)
