### ISSUE TITLE
License

### ISSUE THREAD

**Issue by liuliu** [FreddeFrallan/Multilingual-CLIP#27]
Hi!

While preparing attribution, I noticed that this repo claimed to be licensed under MIT License, but there is no such file: https://github.com/FreddeFrallan/Multilingual-CLIP#license.

Could it be possible to add that file? Thanks!

Also, does that mean the fine-tuned weights (I believe only the linear transformation, other parts are just from FAIR's original release?) is under the same license?

Thank you for your effort and clarifications!

**Comment by rom1504** [comment]
done and yes the weights are under that license
