### ISSUE TITLE
have you tried some new LLMs like vicuna-13b?

### ISSUE THREAD

**Issue by ldfandian** [FreddeFrallan/Multilingual-CLIP#30]
Hello~

Based on my understanding, its major improvement is to retrain a new text encoder using a more multi-lingual friendly LLM. Am I right here?

Recently, some new LLMs like vicuna-13b also show good capability on multi-lingual embedding. do you think it is a good idea to bridge clip visual encoder to those new LLM?

**Comment by floschne** [comment]
@ldfandian Since Vicuna is a decoder-only model, I don't think it can be used (out-of-the-box) to compute embeddings. Can you forward the paper where you got that information? (I know there is work on embeddings from decoder models but I am aware of Vicuna / Llama style models)

**Comment by ldfandian** [comment]
> @ldfandian Since Vicuna is a decoder-only model, I don't think it can be used (out-of-the-box) to compute embeddings. Can you forward the paper where you got that information? (I know there is work on embeddings from decoder models but I am aware of Vicuna / Llama style models)

You are right~ My misunderstanding.
